### ISSUE TITLE
Cannot select [] with dates as index

### ISSUE THREAD

**Issue by dennyglee** [databricks/koalas#287] opened 2019-05-09 17:26 UTC
Run the query:
```
kdf[0:3]
```
and get the error:
```
AttributeError: module 'pyarrow.pandas_compat' has no attribute 'make_datetimetz'
```

To recreate `kdf`:
```
dates = pd.date_range('20130101', periods=6)
pdf = pd.DataFrame(np.random.randn(6,4), index=dates, columns=list('ABCD'))
kdf = ks.from_pandas(pdf)
```

**Comment by rxin** [comment] 2019-05-15 04:59
cc @ueshin @HyukjinKwon can one of you look into this for the next release?

**Comment by HyukjinKwon** [comment] 2019-05-16 09:44
I think it's non-trivial to implement all slicing cases. If I am not mistaken, we can reuse `iloc` for this support and it can be almost a duplicate of #247

**Comment by HyukjinKwon** [comment] 2020-03-12 03:26
Made a PR at #1336

**Closed** 2020-03-13 00:33 UTC
