### ISSUE TITLE
Handling missing values in datatime field throws error.

### ISSUE THREAD

**Issue by apremgeorge** [databricks/koalas#1425] opened 2020-04-15 23:12 UTC
I have the missing values in datetime column in koalas dataframe, 
```
cleaned_Data['Valuation_Date'].head()
(1) Spark Jobs
Out[12]: 0     1/01/2013 0:00
1    16/08/2013 0:00
2    16/08/2013 0:00
3               None
4               None
Name: Valuation_Date, dtype: object
```
I convert to koalas datatime, but thats not working, thorwing error
```
cleaned_Data["Valuation_Date1"] = ks.to_datetime(cleaned_Data["Valuation_Date"], errors='coerce')
cleaned_Data['Valuation_Date1'].head()

org.apache.spark.SparkException: Exception thrown in awaitResult: 
Py4JJavaError                             Traceback (most recent call last)
/databricks/python/lib/python3.7/site-packages/IPython/core/formatters.py in __call__(self, obj)
    700                 type_pprinters=self.type_printers,
    701                 deferred_pprinters=self.deferred_printers)
--> 702             printer.pretty(obj)
    703             printer.flush()
    704             return stream.getvalue()

/databricks/python/lib/python3.7/site-packages/IPython/lib/pretty.py in pretty(self, obj)
    400                         if cls is not object \
    401                                 and callable(cls.__dict__.get('__repr__')):
--> 402                             return _repr_pprint(obj, self, cycle)
    403 
    404             return _default_pprint(obj, self, cycle)

/databricks/python/lib/python3.7/site-packages/IPython/lib/pretty.py in _repr_pprint(obj, p, cycle)
    695     """A pprint that just redirects to the normal repr function."""
    696     # Find newlines and replace them with p.break_()
--> 697     output = repr(obj)
    698     for idx,output_line in enumerate(output.splitlines()):
```
Any help on error please, if there is no missing values then same works charm.

**Comment by ueshin** [comment] 2020-04-16 06:22
What environment are you working on? Seems like it's working in my local.

```py
>>> kdf
    Valuation_Date
0   1/01/2013 0:00
1  16/08/2013 0:00
2  16/08/2013 0:00
3             None
4             None
>>> kdf['Valuation_Date1'] = ks.to_datetime(kdf['Valuation_Date'], errors='coerce')
>>> kdf['Valuation_Date1'].head()
0   2013-01-01
1   2013-08-16
2   2013-08-16
3          NaT
4          NaT
Name: Valuation_Date1, dtype: datetime64[ns]
```

**Comment by apremgeorge** [comment] 2020-04-17 01:11
I am working in Databricks us-west-2c, Thanks

**Comment by ueshin** [comment] 2020-04-17 01:22
Thanks for letting me know.
I tried my example above on Databricks, but it still worked.

It would be really helpful if you could share a simple reproducible example.

**Comment by apremgeorge** [comment] 2020-04-17 01:39
![image](https://user-images.githubusercontent.com/30790120/79522838-1f82a600-80a0-11ea-929c-288ad6a4c76c.png)

**Comment by ueshin** [comment] 2020-04-17 18:21
So I need an example where I can reproduce the error to investigate.
Can I ask some questions?

- Do you see any difference between my example and yours?
- How did you create the `cleaned_Data`?
- Is it possible to share the whole stack trace?

also,

- What version of Databricks Runtime are you working on?
- Did you install any other libraries?

Thanks!

**Comment by HyukjinKwon** [comment] 2020-05-07 00:40
I am closing this due to no feedback.

**Closed by HyukjinKwon** 2020-05-07 00:40 UTC
