### ISSUE TITLE
Add support for columns with dots in the name

### ISSUE THREAD

**Issue by lokijota** [databricks/koalas#369] opened 2019-05-21 14:51 UTC
I have a CSV with a header line like this:

sex, age, n, mean, s.d.

And when doing:

df = k.read_csv(file)

I get:

org.apache.spark.sql.AnalysisException: syntax error in attribute name:  s.d.;

**Comment by HyukjinKwon** [comment] 2019-05-21 14:53
I think this is a duplicate of https://github.com/databricks/koalas/issues/217 .I am sure the root cause is the same or similar for now.

**Comment by lokijota** [comment] 2019-05-21 15:04
Possibly. The error is generated on the next line, btw:

df.columns = ["sex", "age", "n", "mean", "sd"]

and the stack trace is:

AnalysisException: 'syntax error in attribute name:  s.d.;'

During handling of the above exception, another exception occurred:

KeyError                                  Traceback (most recent call last)
<command-3743966018611259> in <module>()
     16 
     17     df = pd.read_csv(file)
---> 18     df.columns = ["sex", "age", "n", "mean", "sd"]
     19     df = df.loc[df['age'] >= 18]
     20     df['n*mean'] = df['n'] * df['mean']

/databricks/python/lib/python3.6/site-packages/databricks/koalas/frame.py in columns(self, names)
   1911         sdf = self._sdf.select(self._metadata.index_columns +
   1912                                [self[old_name]._scol.alias(new_name)
-> 1913                                 for (old_name, new_name) in zip(old_names, names)])
   1914         self._sdf = sdf
   1915         self._metadata = self._metadata.copy(data_columns=names)

/databricks/python/lib/python3.6/site-packages/databricks/koalas/frame.py in <listcomp>(.0)
   1911         sdf = self._sdf.select(self._metadata.index_columns +
   1912                                [self[old_name]._scol.alias(new_name)
-> 1913                                 for (old_name, new_name) in zip(old_names, names)])
   1914         self._sdf = sdf
   1915         self._metadata = self._metadata.copy(data_columns=names)

/databricks/python/lib/python3.6/site-packages/databricks/koalas/frame.py in __getitem__(self, key)
   2632 
   2633     def __getitem__(self, key):
-> 2634         return self._pd_getitem(key)
   2635 
   2636     def __setitem__(self, key, value):

/databricks/python/lib/python3.6/site-packages/databricks/koalas/frame.py in _pd_getitem(self, key)
   2580                               index=self._metadata.index_map)
   2581             except AnalysisException:
-> 2582                 raise KeyError(key)
   2583         if np.isscalar(key) or isinstance(key, (tuple, str)):
   2584             raise NotImplementedError(key)

KeyError: ' s.d.'

**Comment by HyukjinKwon** [comment] 2019-05-24 10:53
Let me leave it as duplicate of #217

**Closed by HyukjinKwon** 2019-05-24 10:53 UTC
Labels: duplicate
