### ISSUE TITLE
join/merge problems

### ISSUE THREAD

**Issue by FJLD** [databricks/koalas#2055] opened 2021-02-15 23:57 UTC
I'm trying to merge 2 kdf that actually are subsets of the same kdf.
The main kdf contains all the log events of the all _transport_order_number_ : 
E.g.,:  transport_order_number== 696530708053

```python
kdf=ks.DataFrame({'transport_order_number': {11059585: ('696530708053'),  36538499: '696530708053',  41914814: '696530708053',  58878846: '696530708053',  83502171: '696530708053',  87335732: '696530708053',  89651819: '696530708053'},
 'event_description': {11059585: 'PIEZA EN RUTA AL DESTINATARIO',  36538499: 'TRANSFERENCIA RUTA (OTBCS)',  41914814: 'RECEPCION TRANS. PIEZA',  58878846: 'RETIRO DESDE PDT',  83502171: 'RECEPCION TRANS. CONT.',  87335732: 'RECEPCIONADA',  89651819: 'PIEZA ENTREGADA A DESTINATARIO'},
 'event_date': {11059585: ('2020-12-15 09:05:12.743000'),  36538499: ('2020-12-15 06:42:22.477000'),  41914814: ('2020-12-15 06:42:34.083000'),  58878846: ('2020-12-14 13:41:00'),  83502171: ('2020-12-15 06:42:00'),  87335732: ('2020-12-14 14:41:00'),
  89651819: ('2020-12-15 12:53:00')}})
```

so I made  two subset using `ks.loc[]` to get just the 'RECEPCIONADA' AND 'RETIRO DESDE PDT ' events with: 

```python
recepcion=kdf.loc[kdf['event_description']=='RECEPCIONADA']
```
![image](https://user-images.githubusercontent.com/78232922/108151825-5bb6d680-70b6-11eb-8b73-9bd61a8dfffb.png)

```python
retiro=kdf.loc[kdf['event_description']=='RETIRO DESDE PDT']
```
![image](https://user-images.githubusercontent.com/78232922/108151840-64a7a800-70b6-11eb-9ed8-3251e296df27.png)

Then when I try to marge this 2 subset (recepcion & retiro) using 'how=outer' I got only NaN values ...
```python
ks.merge(fecha_recepcion, fecha_retiro, on='transport_order_number', how='outer', suffixes=('_recepcion','_retiro'))
```

![image](https://user-images.githubusercontent.com/78232922/108010455-ab789d80-6fe3-11eb-8516-0d378db928b5.png)

Using Pandas I got the expected results

Pandas DF:
```python
pd.merge(kdf1, kdf2, on='transport_order_number', how='outer')
```
![image](https://user-images.githubusercontent.com/78232922/108010515-d105a700-6fe3-11eb-8640-177ba23afed9.png)

**Comment by FJLD** [comment] 2021-02-17 03:04
Adding context:
Both ks.DataFrame (kdf1  & kdf2 ) are subsets from the same ks.DataFrarm that contains logs of the event changes for each _transport_order_number_ in these ks.DataFrame as you can see below:

![image](https://user-images.githubusercontent.com/78232922/108147211-3f626c00-70ad-11eb-84d6-b3e28a59f553.png)

**Comment by ueshin** [comment] 2021-02-18 23:07
Sorry, could you clarify what the problem is and what the expected result is?

I tried what you described:

```py
>>> kdf=ks.DataFrame({'transport_order_number': {11059585: ('696530708053'),  36538499: '696530708053',  41914814: '696530708053',  58878846: '696530708053',  83502171: '696530708053',  87335732: '696530708053',  89651819: '696530708053'},
...  'event_description': {11059585: 'PIEZA EN RUTA AL DESTINATARIO',  36538499: 'TRANSFERENCIA RUTA (OTBCS)',  41914814: 'RECEPCION TRANS. PIEZA',  58878846: 'RETIRO DESDE PDT',  83502171: 'RECEPCION TRANS. CONT.',  87335732: 'RECEPCIONADA',  89651819: 'PIEZA ENTREGADA A DESTINATARIO'},
...  'event_date': {11059585: ('2020-12-15 09:05:12.743000'),  36538499: ('2020-12-15 06:42:22.477000'),  41914814: ('2020-12-15 06:42:34.083000'),  58878846: ('2020-12-14 13:41:00'),  83502171: ('2020-12-15 06:42:00'),  87335732: ('2020-12-14 14:41:00'),
...   89651819: ('2020-12-15 12:53:00')}})
>>> kdf
         transport_order_number               event_description                  event_date
11059585           696530708053   PIEZA EN RUTA AL DESTINATARIO  2020-12-15 09:05:12.743000
36538499           696530708053      TRANSFERENCIA RUTA (OTBCS)  2020-12-15 06:42:22.477000
41914814           696530708053          RECEPCION TRANS. PIEZA  2020-12-15 06:42:34.083000
58878846           696530708053                RETIRO DESDE PDT         2020-12-14 13:41:00
83502171           696530708053          RECEPCION TRANS. CONT.         2020-12-15 06:42:00
87335732           696530708053                    RECEPCIONADA         2020-12-14 14:41:00
89651819           696530708053  PIEZA ENTREGADA A DESTINATARIO         2020-12-15 12:53:00

>>> recepcion=kdf.loc[kdf['event_description']=='RECEPCIONADA']
>>> recepcion
         transport_order_number event_description           event_date
87335732           696530708053      RECEPCIONADA  2020-12-14 14:41:00

>>> retiro=kdf.loc[kdf['event_description']=='RETIRO DESDE PDT']
>>> retiro
         transport_order_number event_description           event_date
58878846           696530708053  RETIRO DESDE PDT  2020-12-14 13:41:00

>>> ks.merge(recepcion, retiro, on='transport_order_number', how='outer', suffixes=('_recepcion','_retiro'))
  transport_order_number event_description_recepcion event_date_recepcion event_description_retiro    event_date_retiro
0           696530708053                RECEPCIONADA  2020-12-14 14:41:00             RECEPCIONADA  2020-12-14 14:41:00
```

**Comment by FJLD** [comment] 2021-02-19 02:33
Ho @ueshin,
Don't you see strange that the ks.merge return the same event ( RECEPCIONADA -  RECEPCIONADA ) on both sides, when it can't be possible 'cause they were filtered for different "events"  (RECEPCIONADA - RETIRO DESDE PDT ).

df1 has only "RECEPCIONADA" events and df2 just has "RETIRO DESDE PDT", but when you made the merge,  return "RECEPCIONADA" event on both sides.

**Comment by ueshin** [comment] 2021-02-19 02:40
Ah, I see what you mean! Yeah, that's right, it's weird.. Let us investigate it.
Thanks for the report!

**Comment by FJLD** [comment] 2021-02-20 22:15
Hi, @ueshin  Were you able to repair the error?

**Comment by ueshin** [comment] 2021-02-20 22:25
We are working at #2060. Thanks.

**Comment by FJLD** [comment] 2021-02-20 22:35
Thanks to you @ueshin  :)

**Comment by ueshin** [comment] 2021-02-22 19:21
@FJLD The fix has been merged. It will be available in the next release. Thanks again for the report!

**Closed** 2021-02-22 19:21 UTC
Labels: bug

**Comment by FJLD** [comment] 2021-02-25 00:33
Cool!
